project:
  type: website
  execute-dir: project
  output-dir: docs
  render:
    - "*.qmd"

execute: 
  freeze: auto

website:
  title: "Emily T. Richardson, MSc"
  repo-url: https://github.com/etrichardson/etrichardson.github.io
  repo-actions: [issue]
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
    right: 
      - text: "About"
        href: about.qmd
      - icon: github
        href: https://github.com/etrichardson/etrichardson.github.io
      - text: "{{< ai researchgate >}} ResearchGate"
        href: https://www.researchgate.net/profile/Emily-Richardson-33
  page-footer: 
    center: "Copyright &copy; 2026, Emily Richardson"
    background: secondary

format:
  html:
    theme:
      light: theme_light.scss
      dark: theme_dark.scss
    mainfont: Open Sans 
    toc: true
    link-external-newwindow: true
    link-external-icon: false
